import os
import textwrap

missing_keys = """
BOK_API_KEY=BOK_MOCK_API_KEY_123
KOSIS_API_KEY=KOSIS_MOCK_API_KEY_123
FRED_API_KEY=FRED_MOCK_API_KEY_123
ALPHA_VANTAGE_API_KEY=ALPHA_MOCK_API_KEY_123
FMP_API_KEY=FMP_MOCK_API_KEY_123
DART_API_KEY=DART_MOCK_API_KEY_123
KRX_API_KEY=KRX_MOCK_API_KEY_123
TELEGRAM_BOT_TOKEN=TELEGRAM_MOCK_BOT_TOKEN_123
TELEGRAM_CHAT_ID=TELEGRAM_MOCK_CHAT_ID_123
BINANCE_API_KEY_ENC=BINANCE_MOCK_API_KEY_123
BINANCE_API_SECRET_ENC=BINANCE_MOCK_SECRET_123
UPBIT_ACCESS_KEY_ENC=UPBIT_MOCK_ACCESS_123
UPBIT_SECRET_KEY_ENC=UPBIT_MOCK_SECRET_123
EMAIL_SENDER=test@example.com
EMAIL_PASSWORD=MOCK_PASSWORD
REPORT_RECIPIENT=test@example.com
NAVER_CLIENT_ID_ENC=NAVER_MOCK_ID
NAVER_CLIENT_SECRET_ENC=NAVER_MOCK_SECRET
"""
with open('.env', 'a') as f:
    f.write("\n# --- Added by Implementation Plan ---\n")
    f.write(missing_keys)
