#!/usr/bin/env python3
import json
import math
import logging
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
_RESULTS = _PROJECT_ROOT / 'results'
_CACHE_FILE = _RESULTS / 'signal_cache.json'

def compute_vix_metrics(vix: float, vix_ma: float, vix_std: float):
    if vix_std <= 0:
        vix_std = 2.0
    z_score = (vix - vix_ma) / vix_std
    cdf = 0.5 * (1.0 + math.erf(z_score / math.sqrt(2.0)))
    v0 = 0.5
    k = 3.0
    logistic_score = 1.0 / (1.0 + math.exp(-k * (z_score - v0)))
    return z_score, cdf, logistic_score

def generate_report():
    if not _CACHE_FILE.exists():
        logger.error("signal_cache.json not found.")
        return

    try:
        cache = json.loads(_CACHE_FILE.read_text())
    except Exception as e:
        logger.error(f"Failed to read signal_cache.json: {e}")
        return

    vix = float(cache.get('vix', 20.0))
    vix_ma = float(cache.get('vix_ma_20', vix))
    vix_std = float(cache.get('vix_std_20', 2.0))
    
    z_score, cdf, logistic_score = compute_vix_metrics(vix, vix_ma, vix_std)
    
    atr_5m = float(cache.get('atr_5m', 0.0))
    s1_adjust = cache.get('kr_stream_adjustments', {}).get('S1', 1.0)

    today_str = datetime.now().strftime('%Y%m%d')
    report_file = _RESULTS / f'Daily_Quant_Report_{today_str}.md'

    content = f"""# Project Meridian - Daily Quant Report ({today_str})

## 📊 VIX Dynamics
* **VIX Current**: {vix:.2f}
* **VIX MA (20)**: {vix_ma:.2f}
* **VIX Std (20)**: {vix_std:.2f}

### 📈 Computed Metrics
* **Z-Score**: {z_score:.3f}
* **Z-Score CDF**: {cdf:.2%}
* **Logistic Score**: {logistic_score:.3f} (Threshold penalty)

## 🎯 S1 Sniper Thresholds
* **Base Threshold Multiplier**: {s1_adjust:.3f}
* **ATR (5m)**: {atr_5m:.5f}

_Auto-generated by Project Meridian Daily Quant Reporting Engine._
"""

    report_file.write_text(content)
    print(f"Generated {report_file}")

if __name__ == "__main__":
    generate_report()
